### ISSUE TITLE
Encounter error (404 not found) while running `./prepare.sh -j`

### ISSUE THREAD

**Issue by tanchihpin0517** [chrisdonahue/sheetsage#12]
As title. It looks like something missing on the data server?

Here is the log:
```
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_HANDCRAFTED_HARMONY_CFG
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0919_02_e0908_oafmelspecnorm/5b739ce5efa2b6d4d70c5f1feac802684f0ee6f4.cfg.json
INFO:root:Verified!
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_HANDCRAFTED_HARMONY_MODEL
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0919_02_e0908_oafmelspecnorm/model.pt
INFO:root:Verified!
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_HANDCRAFTED_HARMONY_STEP
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0919_02_e0908_oafmelspecnorm/step.pkl
INFO:root:Verified!
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_HANDCRAFTED_MELODY_CFG
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0919_00_e0830_oafmelspecnorm/7d82e6839e582936ea428a823a0d868075a52dc5.cfg.json
INFO:root:Verified!
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_HANDCRAFTED_MELODY_MODEL
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0919_00_e0830_oafmelspecnorm/model.pt
INFO:root:Verified!
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_HANDCRAFTED_MELODY_STEP
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0919_00_e0830_oafmelspecnorm/step.pkl
INFO:root:Verified!
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_HANDCRAFTED_MOMENTS
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/oafmelspec_moments.npy
INFO:root:Verified!
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_JUKEBOX_HARMONY_CFG
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0920_01_e0908_jukebox53/f94f45ed03c8696f187a8bfded0f0d65476b4d48.cfg.json
INFO:root:Downloading from: https://nlp.stanford.edu/data/cdonahue/sheetsage/sheetsage/v0.2/0920_01_e0908_jukebox53/f94f45ed03c8696f187a8bfded0f0d65476b4d48.cfg.json
ERROR:root:Download failed: HTTP Error 404: Not Found
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_JUKEBOX_HARMONY_STEP
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0920_01_e0908_jukebox53/step.pkl
INFO:root:Downloading from: https://nlp.stanford.edu/data/cdonahue/sheetsage/sheetsage/v0.2/0920_01_e0908_jukebox53/step.pkl
ERROR:root:Download failed: HTTP Error 404: Not Found
INFO:root:--------------------------------------------------------------------------------
INFO:root:Verifying asset: SHEETSAGE_V02_JUKEBOX_MELODY_MODEL
INFO:root:Asset location: /sheetsage/cache/sheetsage/v0.2/0920_00_e0830_jukebox53/model.pt
INFO:root:Downloading from: https://nlp.stanford.edu/data/cdonahue/sheetsage/sheetsage/v0.2/0920_00_e0830_jukebox53/model.pt
ERROR:root:Download failed: HTTP Error 404: Not Found
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/sheetsage/sheetsage/assets.py", line 120, in retrieve_asset
    _download(url, path)
  File "/sheetsage/sheetsage/assets.py", line 46, in _download
    r = urllib.request.urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/sheetsage/sheetsage/assets.py", line 162, in task
    raise e
  File "/sheetsage/sheetsage/assets.py", line 159, in task
    retrieve_asset(t, delete_wrong=args.delete_wrong)
  File "/sheetsage/sheetsage/assets.py", line 124, in retrieve_asset
    raise Exception(f"Download failed: {e}")
Exception: Download failed: HTTP Error 404: Not Found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sheetsage/sheetsage/assets.py", line 165, in <module>
    p.map(task, tags)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
Exception: Download failed: HTTP Error 404: Not Found
```

**Comment by designzwang** [comment]
HI @tanchihpin0517 ,
the download problem is fixed , but the docker image is not yet adapted to use the new URLs. So you need to fiddle a bit - see my instructions in the issue #9 thread.
   https://github.com/chrisdonahue/sheetsage/issues/9

Regards,
Ulrich

**Comment by tanchihpin0517** [comment]
Got it. Thank you!
