### ISSUE TITLE
Failed to retrieve audio from youtube

### ISSUE THREAD

**Issue by vaclavmuller** [chrisdonahue/sheetsage#19]
vboxuser@ubuntu22:~/sheetsage$ ./sheetsage.sh https://www.youtube.com/watch?v=uYlA0lG_tRU
Running Sheet Sage via Docker with args: https://www.youtube.com/watch?v=uYlA0lG_tRU
INFO:root:FETCHING_AUDIO
INFO:root:Retrieving audio from https://www.youtube.com/watch?v=uYlA0lG_tRU
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
	"__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
	exec(code, run_globals)
  File "/sheetsage/sheetsage/infer.py", line 851, in <module>
	tqdm=tqdm,
  File "/sheetsage/sheetsage/infer.py", line 634, in sheetsage
	audio_path_or_bytes = retrieve_audio_bytes(audio_path_bytes_or_url)
  File "/sheetsage/sheetsage/utils.py", line 204, in retrieve_audio_bytes
	raise Exception(f"Failed to retrieve from {url}:\n{stderr}\n{stdout}")
Exception: Failed to retrieve from https://www.youtube.com/watch?v=uYlA0lG_tRU:
ERROR: [youtube] uYlA0lG_tRU: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] uYlA0lG_tRU: Downloading webpage
[youtube] uYlA0lG_tRU: Downloading android player API JSON

**Comment by vaclavmuller** [comment]
Thanks for this solution: https://github.com/chrisdonahue/sheetsage/pull/20
It works for me.
